name: Basic Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: "Run eslint / type-check / test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: '.tool-versions'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: eslint
        run: pnpm lint
      - name: tsc
        run: pnpm type-check
      - name: test
        run: pnpm test
